# Generated by Django 5.2.7 on 2025-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
